@startuml

participant "Client" as client
participant "Authorisation Server" as authorisation_server

client -> authorisation_server: **Endpoint: /authorisation** \n Sends authorisation code request with \n the code challenge, as well as the \n transformation used to make the code \n challenge from the code verifier.
note right
 Authorisation server makes a
 note of the code challenge and
 the transformation the client
 used.
end note
authorisation_server -> client: Sends authorisation code
client -> authorisation_server: **Endpoint: /token** \n Uses authorisation code to retrieve \n access token, sends the code verifier
note right
 Authorisation server transforms the
 code verifier using the transformation
 it noted earlier. Compares the final
 result to the code challenge the client
 sent in the first step.
end note
authorisation_server -> client: Sends back an access token

@enduml