@startuml

participant "Client" as client
participant "Authorisation Server" as authorisation_server
participant "Resource Owner" as resource_owner
participant "Resource Server" as resource_server

client -> resource_owner: Authorization Request
resource_owner --> client: Authorization Grant

client -> authorisation_server: Authorization Grant
authorisation_server -> client: Access Token

client -> resource_server: Protected Resource Request with Access Token
resource_server -> client: Resource

@enduml