@startuml

participant "Relying Party" as relying_party
participant "Open ID Provider \n Authorization Server" as open_id_provider
participant "End User" as end_user

relying_party -> open_id_provider: **Endpoint: /authorize:** Sends authorization request as \n with OAuth2.0, including OIDC scope
open_id_provider -> end_user: Authenticates and asks for \n authorisation from
open_id_provider -> relying_party: Sends authorisation response to, the relying \n party now has the OIDC scope.
relying_party -> open_id_provider: Sends user info request to
open_id_provider -> relying_party: Sends user info response to

@enduml